### ISSUE TITLE
GuzzleSender::createResponse(): Argument #2 ($guzzleResponse) must be of type Psr\Http\Message\ResponseInterface, null given

### ISSUE THREAD

**Issue by MarienMupenda** [Sammyjo20/Saloon#188]
Hi, I am trying to use the SoloRequest as shown in the [documentation](https://docs.saloon.dev/digging-deeper/solo-requests) but here is what i get : 

<img width="909" alt="image" src="https://user-images.githubusercontent.com/57844897/227015583-a13a3a90-0ed3-4f36-8402-e9aa039d6031.png">

**Code definition** :
![image](https://user-images.githubusercontent.com/57844897/227016092-355d6277-7051-4bc1-b055-43c88ff4ae00.png)

**Then** :
![image](https://user-images.githubusercontent.com/57844897/227017011-45811ae7-c03f-4ff8-8658-3329d827c54c.png)

Am i missing something?

PHP 8.1
Laravel 10.4
Saloon 2.4

**Comment by Sammyjo20** [comment]
Hey @MarienMupenda I will do some investigation for you. 

Are you using the Laravel HTTP sender package or are you just using the default sender that comes with Saloon? If you don't have `sammyjo20/saloon-http-sender` installed in your composer.json you are probably just using the default Guzzle sender.

**Comment by MarienMupenda** [comment]
Yeah it's working now, after installing `sammyjo20/saloon-http-sender`.

Thank you @Sammyjo20 !

<img width="960" alt="image" src="https://user-images.githubusercontent.com/57844897/227053513-462e1373-f315-4fda-bcc4-aac1c4bb869a.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/57844897/227053808-4e496a13-ca3d-4242-82b1-986ce0b78961.png">

**Comment by Sammyjo20** [comment]
Hey @MarienMupenda that's great, and it isn't... I'll see if there's an issue with the normal Guzzle sender. :)

**Comment by heikokrebs** [comment]
Hey @Sammyjo20 i am seeing a lot of the errors as well. Currently i am not using `sammyjo20/saloon-http-sender`.

What surprises me is that I don't always get this error, a lot of the requests work without any problems. But in an error case unknown to me so far, when some unforeseen response comes, it seems to come to this error...!?

**Comment by Sammyjo20** [comment]
Hey @heikokrebs thanks for letting me know - this is very strange. So just to clarify, this may be able to be replicated by using Laravel but not the HTTP sender, so internally it'll use the Guzzle sender? This is very strange because I've not seen this error in any of my testing. 

What version of Laravel are you using? Are you using Saloon v1 or v2?

**Comment by heikokrebs** [comment]
@Sammyjo20 i am using Saloon v2 and Laravel 10.9.0

Yes, until now i am using Saloon without the HTTP Sender, so with the guzzle sender.
I will switch now a have a look if something changes.

**Comment by heikokrebs** [comment]
If this helps:

```
[2023-05-08 22:09:33] production.ERROR: Saloon\Http\Senders\GuzzleSender::createResponse(): Argument #2 ($guzzleResponse) must be of type Psr\Http\Message\ResponseInterface, null given, called in …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php on line 120 {"exception":"[object] (TypeError(code: 0): Saloon\\Http\\Senders\\GuzzleSender::createResponse(): Argument #2 ($guzzleResponse) must be of type Psr\\Http\\Message\\ResponseInterface, null given, called in …/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php on line 120 at …/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php:204)
```

**Comment by Sammyjo20** [comment]
Thanks @heikokrebs this helps a lot - any idea of what the API error could be? I wonder if I'm not catching a specific Guzzle exception, or perhaps I'm not catching a non-guzzle Exception like if your application throws an exception in a middleware or something like that.

**Comment by heikokrebs** [comment]
@Sammyjo20 is suspect it is a 500 Error. i am using a proxy service to crawl a site and sometimes it ist blocked and responds with an 500.

I am actually handling this error like this (inside an queue job):

```
if ($response->failed()) {
                if ($response->status() === Response::HTTP_INTERNAL_SERVER_ERROR) {
                    $this->release(rand(1, 5));
                    return;
                }

                $this->fail($response->body());
                return;
}
```

**Comment by heikokrebs** [comment]
I have another suspicion, perhaps it is also connected with the SSL verification. 
The requested url where it was noticed had a self signed cert which led to the error. Since the request was made within a laravel job, the job was simply retried.

However, it is not clear to me why this error occurs with the response...

Here is the full trace:

```
[2023-05-08 22:09:33] production.ERROR: Saloon\Http\Senders\GuzzleSender::createResponse(): Argument #2 ($guzzleResponse) must be of type Psr\Http\Message\ResponseInterface, null given, called in …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php on line 120 {"exception":"[object] (TypeError(code: 0): Saloon\\Http\\Senders\\GuzzleSender::createResponse(): Argument #2 ($guzzleResponse) must be of type Psr\\Http\\Message\\ResponseInterface, null given, called in …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php on line 120 at …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php:204)
[stacktrace]
#0 …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php(120): Saloon\\Http\\Senders\\GuzzleSender->createResponse()
#1 …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Senders/GuzzleSender.php(91): Saloon\\Http\\Senders\\GuzzleSender->sendSynchronousRequest()
#2 …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/Dispatcher.php(40): Saloon\\Http\\Senders\\GuzzleSender->sendRequest()
#3 …/releases/20230508194427/vendor/sammyjo20/saloon/src/Http/PendingRequest.php(479): Saloon\\Http\\Dispatcher->execute()
#4 …/releases/20230508194427/vendor/sammyjo20/saloon/src/Traits/Connector/SendsRequests.php(33): Saloon\\Http\\PendingRequest->send()
#5 …/releases/20230508194427/app/Jobs/Ebay/Account/CollectAccountStatistics.php(85): Saloon\\Http\\Connector->send()
#6 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\Ebay\\Account\\CollectAccountStatistics->handle()
#7 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#11 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#12 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#13 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#15 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#16 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#17 …/releases/20230508194427/vendor/spatie/laravel-rate-limited-job-middleware/src/RateLimited.php(173): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(91): Spatie\\RateLimitedMiddleware\\RateLimited->Spatie\\RateLimitedMiddleware\\{closure}()
#19 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(133): Illuminate\\Redis\\Limiters\\DurationLimiter->block()
#20 …/releases/20230508194427/vendor/spatie/laravel-rate-limited-job-middleware/src/RateLimited.php(176): Illuminate\\Redis\\Limiters\\DurationLimiterBuilder->then()
#21 …/releases/20230508194427/vendor/spatie/laravel-rate-limited-job-middleware/src/RateLimited.php(157): Spatie\\RateLimitedMiddleware\\RateLimited->handleRedis()
#22 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\RateLimitedMiddleware\\RateLimited->handle()
#23 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#25 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#26 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#27 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(434): Illuminate\\Queue\\Jobs\\Job->fire()
#28 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(384): Illuminate\\Queue\\Worker->process()
#29 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(175): Illuminate\\Queue\\Worker->runJob()
#30 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(137): Illuminate\\Queue\\Worker->daemon()
#31 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#32 …/releases/20230508194427/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#33 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#34 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#36 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#38 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#39 …/releases/20230508194427/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#40 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Console/Command.php(164): Symfony\\Component\\Console\\Command\\Command->run()
#41 …/releases/20230508194427/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#42 …/releases/20230508194427/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#43 …/releases/20230508194427/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#44 …/releases/20230508194427/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#45 …/releases/20230508194427/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#46 {main}
```

**Comment by danielsdeboer** [comment]
I'm having the same issue in the same place (`GuzzleSender` line 120), which is inside the `catch` block. I dumped out the exception and it is indeed due to a curl error 60:

```
GuzzleHttp\Exception\RequestException {#87
  #message: "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost/***"
  #code: 0
  #file: "./vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php"
  #line: 211
...
}
```

**Comment by danielsdeboer** [comment]
Might be worth inspecting the `handlerContext` of the `RequestException`, looking for errno =  60, and raising some kind of custom exception for this issue. It's a very common thing to hit in local environments and very easy to work around by doing something like `$connector->config()->add('verify', false)` in a test case for example.

Or perhaps another way would be to check if the `RequestException` actually has an attached response and throwing a `FatalRequestException` if not?

**Comment by Sammyjo20** [comment]
Thanks @danielsdeboer I managed to find the issue. Guzzle has some logic which means sometimes it will throw a `RequestException` if it cannot connect properly.

```php
// CurlFactory.php:208

// Create a connection exception if it was a specific error code.
$error = isset($connectionErrors[$easy->errno])
    ? new ConnectException($message, $easy->request, null, $ctx)
    : new RequestException($message, $easy->request, $easy->response, null, $ctx);
```

I've created a PR #216 which should solve this!
